/* Komplette Melder-Enzyklopädie – jeder Sensor mit Physik, Aktiv/Passiv, Stärken, Schwächen, Normen */
window.ENCY = (() => {

  // type: 'passiv' = empfängt nur, 'aktiv' = sendet selbst, 'hybrid' = beides
  // coverage: 'volumetrisch' | 'flaeche' | 'linie' | 'punkt' | 'feld'
  // zone: 1..4 oder mehrere
  const M = [

    // ============= PASSIVE BEWEGUNGS-/RAUMMELDER =============
    {
      key:'pir-standard', kat:'Bewegung', name:'PIR-Melder (Standard)',
      type:'passiv', principle:'Pyroelektrischer Effekt',
      physik:'Erfasst Wärmestrahlung (8–14 µm) bewegter Wärmequellen. Eine Fresnel-Linse teilt das Sichtfeld in schmale Zonen. Das pyroelektrische LiTaO₃-Element erzeugt bei Bewegung wechselnde Spannungsdifferenz.',
      sendet:'nichts – rein empfangend',
      coverage:'volumetrisch · Kegel', range:'12×12 m / 90°',
      zone:[3],
      staerken:['Kein Energieaufwand für Senden','Unauffällig, da keine Strahlung','Hohe Reichweite','Günstig'],
      schwaechen:['Reagiert nur auf Bewegung quer zur Linse','Wärme-Hintergrund senkt Empfindlichkeit','Reagiert nicht durch Glas/Wände'],
      fehlalarm:['Direkte Sonneneinstrahlung','Heizkörper im Sichtfeld','Plötzliche Lüftung warmer Luft','Tiere, Insekten'],
      montage:'Wand 2,0–2,4 m hoch, Blick in den Raum',
      normen:['VdS 2312','DIN EN 50131-2-2','DIN VDE 0833-3'],
      sue:'1-3', preis:'25–80 €',
      hersteller:['Bosch','Honeywell','Telenot'],
      ill:'pir', icon:'fa-eye'
    },
    {
      key:'pir-vorhang', kat:'Bewegung', name:'PIR-Vorhangmelder',
      type:'passiv', principle:'Pyroelektrischer Effekt mit Spezialoptik',
      physik:'Spezielle Fresnel-Maske erzeugt einen sehr schmalen "Vorhang"-Strahl (typ. 6°). Erkennt jedes Durchqueren einer schmalen Linie.',
      sendet:'nichts',
      coverage:'volumetrisch · Linien-Vorhang', range:'2×20 m / 6°',
      zone:[3,2],
      staerken:['Präzise Linien-Detektion','Ideal für Durchgänge','Wenig Fehlalarme'],
      schwaechen:['Sehr eng – muss exakt platziert sein','Blickbereich begrenzt'],
      fehlalarm:['Vorhänge in Zugluft','Bewegliche Möbel'],
      montage:'Wand parallel zum gewünschten Vorhang',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'2-3', preis:'35–100 €',
      hersteller:['Bosch','Optex'],
      ill:'pir', icon:'fa-grip-lines-vertical'
    },
    {
      key:'pir-decke', kat:'Bewegung', name:'PIR-Deckenmelder 360°',
      type:'passiv', principle:'Rundum-Pyroelektrik',
      physik:'Mehrere Pyro-Segmente mit Spezial-Linse erfassen 360° um den Sensor von oben nach unten.',
      sendet:'nichts',
      coverage:'volumetrisch · Kreis von oben', range:'Ø 12 m / 360°',
      zone:[3],
      staerken:['Komplette Rundum-Abdeckung','Unauffällig an der Decke','Schwer zu unterlaufen'],
      schwaechen:['Begrenzte Reichweite','Aufwendige Montage'],
      fehlalarm:['Heißluft-Aufstieg von Lampen','Klima-Anlagen'],
      montage:'Decke 2,5–3,5 m, mittig im Raum',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'2-3', preis:'40–120 €',
      hersteller:['Bosch','ABB','Theben'],
      ill:'pir', icon:'fa-circle-dot'
    },
    {
      key:'pir-longrange', kat:'Bewegung', name:'PIR Long Range',
      type:'passiv', principle:'Pyroelektrik mit gebündelter Optik',
      physik:'Fokussierte Linse erzeugt schmalen, langreichweitigen Erfassungskegel.',
      sendet:'nichts',
      coverage:'linie / langer Kegel', range:'5×30 m',
      zone:[3,1],
      staerken:['Sehr hohe Reichweite','Ideal für Hallen, Korridore'],
      schwaechen:['Sehr schmal','Aufwendigere Justage'],
      fehlalarm:['Sonneneinstrahlung von vorne','Bewegungen an Reichweiten-Grenze'],
      montage:'Wand, exakt ausgerichtet',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'2-4', preis:'50–150 €',
      hersteller:['Optex','Bosch'],
      ill:'pir', icon:'fa-arrows-up-down-left-right'
    },
    {
      key:'pir-tierimmun', kat:'Bewegung', name:'PIR tierimmun',
      type:'passiv', principle:'Pyroelektrik mit Gewichtsfilter',
      physik:'Spezial-Algorithmus + Linsen-Geometrie filtert Wärmemuster von Tieren bis 25 kg heraus. Kleinere Wärmesignaturen lösen keinen Alarm aus.',
      sendet:'nichts',
      coverage:'volumetrisch · Kegel', range:'12×12 m / 90°',
      zone:[3],
      staerken:['Kein Fehlalarm durch Hund/Katze','Für Wohnungen mit Haustieren'],
      schwaechen:['Großer Hund kann doch auslösen','Begrenzte Wirksamkeit bei Kletter-Tieren'],
      fehlalarm:['Tiere >25 kg','Tiere die hochspringen'],
      montage:'Wand 2,0–2,4 m, NICHT auf den Boden gerichtet',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'1-2', preis:'35–100 €',
      hersteller:['Bosch','DSC','Paradox'],
      ill:'pir', icon:'fa-cat'
    },
    {
      key:'pir-antimask', kat:'Bewegung', name:'PIR Anti-Masking',
      type:'passiv (mit aktivem IR-Sabotage-Sensor)', principle:'Pyroelektrik + IR-Reflexion',
      physik:'Klassischer PIR-Melder plus zusätzlicher aktiver IR-Sender/Empfänger, der erkennt, wenn die Linse abgedeckt, übersprüht oder verklebt wird.',
      sendet:'Niedrigleistungs-IR-Puls zur Sabotage-Erkennung',
      coverage:'volumetrisch · Kegel + Linsen-Selbsttest', range:'12×12 m / 90°',
      zone:[3],
      staerken:['Sabotage-resistent','Hohe Sicherungsklasse','Ab Grad 3 / SÜ 4 gefordert'],
      schwaechen:['Teurer','Mehr Stromverbrauch'],
      fehlalarm:['Glas direkt vor Linse','Schmierige Linsen'],
      montage:'Wand 2,0–2,4 m, freie Sicht auf Linse',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'4-6', preis:'100–280 €',
      hersteller:['Bosch','Honeywell','Telenot'],
      ill:'pir', icon:'fa-shield-virus'
    },
    {
      key:'pir-outdoor', kat:'Bewegung', name:'Außen-PIR IP65',
      type:'passiv', principle:'Pyroelektrik mit Wetterschutz',
      physik:'Standard-PIR plus dichtes Gehäuse, Spezial-Linse mit UV-Filter, heizung gegen Beschlag, Algorithmen für Wetter-Stör­einflüsse.',
      sendet:'nichts',
      coverage:'volumetrisch · Kegel, wetterfest', range:'12×12 m, IP65',
      zone:[1,2],
      staerken:['Wetterfest','Sonnenfilter','Frostschutz'],
      schwaechen:['Reagiert immer noch auf Tiere','Reichweite witterungsabhängig'],
      fehlalarm:['Starke Sonneneinstrahlung','Frost / Eisbildung','Schnee'],
      montage:'Fassade, regenabgewandt',
      normen:['VdS 2312','DIN EN 50131-2-2'],
      sue:'2-4', preis:'80–250 €',
      hersteller:['Optex','Ajax','Bosch'],
      ill:'pir', icon:'fa-cloud-sun'
    },

    // ============= AKTIVE BEWEGUNGSMELDER =============
    {
      key:'mikrowelle', kat:'Bewegung', name:'Mikrowellenmelder',
      type:'aktiv', principle:'Doppler-Radar 10,525 GHz',
      physik:'Sender strahlt 10,525 GHz Mikrowellen aus, die von Objekten reflektiert werden. Bewegte Objekte erzeugen eine Frequenzverschiebung (Doppler-Effekt). Sensor mischt Sende- und Empfangssignal → Differenzfrequenz = Geschwindigkeit.',
      sendet:'10,525 GHz X-Band Mikrowellen',
      coverage:'volumetrisch · Doppler-Sphäre', range:'20×20 m',
      zone:[3,2],
      staerken:['Durchdringt Glas/Holz/dünne Wände','Reagiert auf jede Bewegung im Volumen','Lange Reichweite'],
      schwaechen:['"Sieht" durch Wände – Fehlalarme von außen','Anfällig für Vibrationen','Höherer Stromverbrauch'],
      fehlalarm:['Leuchtstoffröhren','Fließendes Wasser in Rohren','Ventilatoren','Bewegung in Nachbarräumen'],
      montage:'Wand oder Ecke, weg von Wasserleitungen',
      normen:['VdS 2312','DIN EN 50131-2-3'],
      sue:'3-4', preis:'80–200 €',
      hersteller:['Bosch','Crow','Optex'],
      ill:'mw', icon:'fa-tower-broadcast'
    },
    {
      key:'dualmelder', kat:'Bewegung', name:'Dualmelder (PIR + MW)',
      type:'hybrid', principle:'AND-Verknüpfung zweier Technologien',
      physik:'Kombiniert passiven PIR-Sensor und aktiven Mikrowellen-Sensor in einem Gehäuse. Beide werden AND-verknüpft – nur wenn BEIDE gleichzeitig auslösen, wird Alarm geschlagen.',
      sendet:'10,525 GHz für den MW-Teil',
      coverage:'volumetrisch · Kegel · UND-Logik', range:'15×15 m / 90°',
      zone:[3,2],
      staerken:['–95 % Fehlalarme','Beste Wahl für Hallen, Werkstätten','Sehr robust gegen Störquellen'],
      schwaechen:['Teurer als Einzelsensoren','Beide Sensorprinzipien müssen frei sein'],
      fehlalarm:['Selten – wenn nur eine Technologie auslöst, kein Alarm'],
      montage:'Wand 2,0–2,4 m',
      normen:['VdS 2312','DIN EN 50131-2-4'],
      sue:'3-5', preis:'60–180 €',
      hersteller:['Bosch','Honeywell','DSC'],
      ill:'dual', icon:'fa-shield-halved'
    },
    {
      key:'ultraschall', kat:'Bewegung', name:'Ultraschallmelder',
      type:'aktiv', principle:'Doppler 40 kHz Schall',
      physik:'Sendet Ultraschall (40 kHz), empfängt reflektierte Wellen. Bewegung in der Luft erzeugt Frequenzverschiebung. Funktioniert nur in geschlossenen Räumen (Schallreflektion).',
      sendet:'40 kHz Ultraschall',
      coverage:'volumetrisch · Raumvolumen', range:'10×10 m',
      zone:[3],
      staerken:['Erkennt jede Luftbewegung','Füllt den Raum komplett','Schwer zu unterlaufen'],
      schwaechen:['Nur in geschlossenen Räumen','Reagiert auf Luftzug','Reichweite begrenzt'],
      fehlalarm:['Zugluft / Klimaanlagen','Laute Geräusche','Schwingende Vorhänge'],
      montage:'Wand 2,0–2,4 m, geschlossener Raum',
      normen:['DIN EN 50131-2-1'],
      sue:'3-4', preis:'50–150 €',
      hersteller:['Bosch','Aritech'],
      ill:'mw', icon:'fa-volume-high'
    },

    // ============= ÖFFNUNGSMELDER =============
    {
      key:'magnetkontakt', kat:'Öffnung', name:'Magnetkontakt (Reed)',
      type:'passiv', principle:'Reed-Kontakt + Permanentmagnet',
      physik:'Magnetfeld eines Permanentmagneten hält zwei magnetisierbare Glasampullen-Zungen zusammen. Geschlossene Tür → Stromkreis geschlossen. Tür öffnet → Magnet weg → Kontakt öffnet → Ruhestrom unterbrochen → Alarm.',
      sendet:'nichts (Magnetfeld wirkt nur kurz)',
      coverage:'punkt (pro Tür/Fenster)', range:'15–25 mm Schaltabstand',
      zone:[2],
      staerken:['Sehr zuverlässig','Sabotagesicher (Ruhestrom)','Günstig','Sehr lange Lebensdauer'],
      schwaechen:['Erkennt nur "offen/zu", nicht verriegelt','Klassische Form mit Fremd-Magnet überbrückbar'],
      fehlalarm:['Schlechte Justage','Verformter Rahmen','Vibrationen lösen kurz aus'],
      montage:'Magnet auf bewegl. Teil, Reed auf festem Rahmen',
      normen:['VdS 2120','DIN EN 50131-2-6'],
      sue:'1-3 (Standard), 4-6 (fremdfeldgesichert)', preis:'8–40 €',
      hersteller:['BKS','Honeywell','Bosch'],
      ill:'mag', icon:'fa-magnet'
    },
    {
      key:'schliessblech', kat:'Öffnung', name:'Schließblech-/Riegelkontakt',
      type:'passiv', principle:'Mechanischer Kontakt im Schließblech',
      physik:'Kontakt im Türrahmen, der vom Schlossriegel betätigt wird. Erkennt – im Gegensatz zum Magnetkontakt – ob die Tür tatsächlich verriegelt ist.',
      sendet:'nichts',
      coverage:'punkt', range:'pro Tür',
      zone:[2],
      staerken:['Erkennt echte Verriegelung','Voraussetzung für Scharfschaltung'],
      schwaechen:['Funktioniert nur bei zugehörigem Schloss-System','Mehr Verkabelung nötig'],
      fehlalarm:['Verschlissener Riegel','Schloss-Defekt'],
      montage:'im Schließblech der Tür',
      normen:['VdS 2269','DIN EN 50131-2-6'],
      sue:'3-6 (PFLICHT)', preis:'35–90 €',
      hersteller:['BKS','Assa Abloy','GU'],
      ill:'mag', icon:'fa-lock'
    },

    // ============= GLASBRUCHMELDER =============
    {
      key:'glas-passiv', kat:'Glasbruch', name:'Passiv-akustischer Glasbruchmelder',
      type:'passiv', principle:'Akustische Frequenzanalyse',
      physik:'Mikrofon analysiert Raumschall: Glasbruch erzeugt charakteristische Doppel-Signatur – niederfrequente Aufprall-/Biegung gefolgt von hochfrequentem Splittern. Beide Phasen müssen vorliegen.',
      sendet:'nichts',
      coverage:'volumetrisch · Schall-Kugel', range:'6 m Radius',
      zone:[2],
      staerken:['Ein Sensor deckt mehrere Scheiben ab','Kosteneffizient','Schwer zu täuschen'],
      schwaechen:['Lauter Hintergrund stört','Nicht zertifiziert für jede Scheibe'],
      fehlalarm:['Hundebellen','Schlüssel-Klimpern','Lärm direkt am Sensor'],
      montage:'Wand/Decke, freie Schalllinie zu allen Scheiben',
      normen:['VdS 2332','DIN EN 50131-2-7'],
      sue:'2-4', preis:'30–80 €',
      hersteller:['Bosch','Honeywell','Telenot'],
      ill:'glass', icon:'fa-volume-low'
    },
    {
      key:'glas-aktiv', kat:'Glasbruch', name:'Aktiv-Folie / Alarmdraht',
      type:'aktiv', principle:'Leiterbahn-Überwachung',
      physik:'Dünne Folie/Draht mit Leiterbahn wird auf die Scheibe geklebt. Niedriger Ruhestrom fließt permanent. Bricht das Glas oder die Folie → Leiterbahn unterbrochen → Alarm.',
      sendet:'permanenter Prüfstrom durch die Folie',
      coverage:'flaeche · pro Scheibe', range:'pro Scheibe einzeln',
      zone:[2],
      staerken:['100 % zuverlässig','Erkennt jeden Riss auch ohne Bruch','Klar zuzuordnen welche Scheibe'],
      schwaechen:['Pro Scheibe einzeln','Optisch sichtbar (Folie/Draht)'],
      fehlalarm:['Folie löst sich','Materialermüdung'],
      montage:'direkt auf der Scheibe',
      normen:['VdS 2332','DIN EN 50131-2-7'],
      sue:'2-4', preis:'15–50 €/Scheibe',
      hersteller:['Geba','Aritech'],
      ill:'glass', icon:'fa-bolt-lightning'
    },
    {
      key:'glas-piezo', kat:'Glasbruch', name:'Piezo-Glasbruchmelder',
      type:'passiv (hochempfindlich)', principle:'Piezo + Schallanalyse direkt am Glas',
      physik:'Piezo-Element direkt auf der Scheibe montiert misst Glas-Vibration + Bruchschall. Erkennt Anbohren, Anschneiden, Bruch.',
      sendet:'nichts',
      coverage:'flaeche · pro Scheibe', range:'pro Scheibe',
      zone:[2],
      staerken:['Erkennt sogar Anbohren/Anschneiden','Sehr zuverlässig','Höchste Sicherheit'],
      schwaechen:['Pro Scheibe ein Sensor','Optisch sichtbar'],
      fehlalarm:['Schwere mechanische Stöße','Erschütterungen'],
      montage:'direkt auf der Scheibe',
      normen:['VdS 2332','DIN EN 50131-2-7'],
      sue:'4-6', preis:'40–120 €',
      hersteller:['Telenot','Honeywell'],
      ill:'glass', icon:'fa-vector-square'
    },

    // ============= ERSCHÜTTERUNGS- / KÖRPERSCHALL =============
    {
      key:'piezo-erschuetterung', kat:'Erschütterung', name:'Piezo-Erschütterungsmelder',
      type:'passiv', principle:'Piezoelektrischer Effekt',
      physik:'Piezokeramik wandelt mechanische Vibration (Bohren, Stemmen, Hebeln) in elektrische Spannung. Schwellwert-Auswertung: erst wenn Amplitude UND Dauer Grenzwerte überschreiten → Alarm.',
      sendet:'nichts',
      coverage:'flaeche · entlang der Oberfläche', range:'~2 m Radius auf gleicher Fläche',
      zone:[2,4],
      staerken:['Erkennt direkten Angriff','Robust','Schwer zu täuschen'],
      schwaechen:['Reagiert nicht auf Bewegung im Raum','Begrenzte Wirkfläche'],
      fehlalarm:['Schwere Türen-Knallen','Vorbeifahrende LKW'],
      montage:'direkt auf zu schützender Fläche (Wand, Tresor, Rahmen)',
      normen:['VdS 2480','DIN EN 50131-2-8'],
      sue:'3-5', preis:'25–70 €',
      hersteller:['Telenot','Bosch'],
      ill:'shake', icon:'fa-bolt'
    },
    {
      key:'koerperschall', kat:'Erschütterung', name:'Körperschallmelder',
      type:'passiv (hochempfindlich)', principle:'Mikrofon + Frequenzanalyse im Material',
      physik:'Hochempfindliches Mikrofon misst Körperschall IM Material (Stahl, Beton). Frequenzanalyse erkennt charakteristische Bohr-/Schneid-/Sprengsignaturen, unterscheidet von Umgebungsgeräuschen.',
      sendet:'nichts',
      coverage:'flaeche · Material-Reichweite', range:'pro Tresorseite',
      zone:[4],
      staerken:['Erkennt Bohren, Schneidbrenner, Trennschleifer, Sprengversuche','Tresor-Standard ab SÜ 5'],
      schwaechen:['Sehr empfindlich, braucht stillen Aufstellort','Teurer'],
      fehlalarm:['Lärm direkt am Tresor','Wartungsarbeiten'],
      montage:'direkt auf dem Tresor',
      normen:['VdS 2480','DIN EN 50131-2-8'],
      sue:'5-6', preis:'60–200 €',
      hersteller:['Telenot','Honeywell','Cerberus'],
      ill:'shake', icon:'fa-waveform'
    },
    {
      key:'seismisch', kat:'Erschütterung', name:'Seismischer Sensor (Tresor)',
      type:'passiv', principle:'Seismische Vibration',
      physik:'Empfindlicher Vibrationssensor, der sehr leise seismische Erschütterungen im Bereich 5–500 Hz erkennt. Kombiniert mit Mustererkennung.',
      sendet:'nichts',
      coverage:'flaeche', range:'pro Tresorwand',
      zone:[4],
      staerken:['Erkennt sehr feine Angriffe','Höchste Empfindlichkeit'],
      schwaechen:['Sehr teuer','Verkabelung kritisch'],
      fehlalarm:['Erdbeben','Straßenverkehr'],
      montage:'direkt auf Tresor / Wand',
      normen:['DIN EN 50131-2-8'],
      sue:'5-6', preis:'150–500 €',
      hersteller:['Cerberus','Securiton'],
      ill:'shake', icon:'fa-tower-broadcast'
    },

    // ============= SPEZIALMELDER =============
    {
      key:'kapazitiv', kat:'Spezial', name:'Kapazitiver Feldmelder',
      type:'aktiv (Feld)', principle:'Elektrostatisches Feld',
      physik:'Erzeugt um das geschützte Objekt ein elektrostatisches Feld. Ein menschlicher Körper bringt seine eigene Kapazität ein und verändert das Feld – bevor er das Objekt berührt.',
      sendet:'elektrostatisches Hochspannungsfeld (sehr niedrige Energie)',
      coverage:'feld · Annäherungs-Hülle', range:'~0,5 m Annäherung',
      zone:[4],
      staerken:['Alarm VOR Berührung!','Höchster Schutz für Tresore, Vitrinen, Kunst','Unsichtbar'],
      schwaechen:['Sehr aufwendig zu installieren','Reagiert auch auf Tiere','Anfällig für Erdung'],
      fehlalarm:['Befeuchtung des Objekts','Insekten','Reinigungs-Arbeiten'],
      montage:'rund um das geschützte Objekt',
      normen:['DIN EN 50131-2-9'],
      sue:'5-6', preis:'100–350 €',
      hersteller:['Geba','Honeywell','Telenot'],
      ill:'cap', icon:'fa-wave-square'
    },
    {
      key:'druckmatte', kat:'Spezial', name:'Druckmatte / Trittmelder',
      type:'passiv', principle:'Kontaktfolien unter Belag',
      physik:'Zwei dünne Folien mit Abstand. Beim Betreten wird der Abstand überdrückt, die Folien berühren sich → Kontakt geschlossen → Alarm.',
      sendet:'nichts',
      coverage:'flaeche · auf der Matte', range:'1–2 m² pro Matte',
      zone:[2,4],
      staerken:['Unsichtbar unter Teppich/Fliesen','100 % zuverlässig','Schwer zu umgehen'],
      schwaechen:['Pro Matte begrenzte Fläche','Aufwendig nachzurüsten'],
      fehlalarm:['Schwere Möbel','Fallende Gegenstände'],
      montage:'unter Bodenbelag',
      normen:['DIN EN 50131-2-6'],
      sue:'4-6', preis:'80–250 €',
      hersteller:['Geba','Aritech'],
      ill:'press', icon:'fa-shoe-prints'
    },
    {
      key:'wassermelder', kat:'Spezial', name:'Wassermelder',
      type:'passiv', principle:'Leitfähigkeit',
      physik:'Zwei Elektroden mit Abstand am Boden. Wasser zwischen beiden schließt den Stromkreis → Alarm.',
      sendet:'kleinen Prüfstrom über die Elektroden',
      coverage:'punkt · Bodenkontakt', range:'pro Sensor',
      zone:[3],
      staerken:['Erkennt Wasserschaden sofort','Sehr günstig'],
      schwaechen:['Reagiert nur bei direktem Kontakt'],
      fehlalarm:['Reinigungs-Arbeiten','Feuchtwischer'],
      montage:'auf dem Boden, tiefste Stelle',
      normen:[],
      sue:'2-4', preis:'20–80 €',
      hersteller:['Bosch','Aqualarm'],
      ill:'press', icon:'fa-droplet'
    },
    {
      key:'gasmelder', kat:'Spezial', name:'Gasmelder (CO / CH₄)',
      type:'aktiv (Sensor heizt)', principle:'Katalytisch / Elektrochemisch',
      physik:'Sensor enthält katalytisches Element, das bei Anwesenheit brennbarer Gase eine Verbrennung erzeugt → Temperaturänderung → Signal.',
      sendet:'Sensor heizt sich selbst (kein externes Signal)',
      coverage:'volumetrisch · Raumluft', range:'pro Raum',
      zone:[3],
      staerken:['Lebensrettend','Erkennt CO/CH₄ in geringen Konzentrationen'],
      schwaechen:['Sensor altert (typ. 5–10 Jahre)','Kalibrierung nötig'],
      fehlalarm:['Lösemittel','Spray-Dosen'],
      montage:'Decke (Methan) / Bodennähe (CO)',
      normen:['DIN EN 50194'],
      sue:'1-3', preis:'30–120 €',
      hersteller:['Honeywell','Kidde'],
      ill:'press', icon:'fa-skull-crossbones'
    },

    // ============= IR-LICHTSCHRANKE =============
    {
      key:'ir-schranke', kat:'Aktiv-IR', name:'IR-Lichtschranke',
      type:'aktiv', principle:'Codierte IR-Pulse',
      physik:'Sender sendet codierte Infrarot-Pulse (940 nm). Empfänger auf der Gegenseite registriert die Pulse. Unterbrechung → Alarm. Codierung verhindert Überbrückung mit externer IR-Quelle.',
      sendet:'gepulste IR-Strahlen 940 nm (unsichtbar)',
      coverage:'linie · Mehrstrahl-Vorhang', range:'5–250 m',
      zone:[1,2,3],
      staerken:['Präzise Linien-Detektion','Schwer zu täuschen (codiert)','Outdoor verfügbar'],
      schwaechen:['Sender + Empfänger benötigt','Strahlen müssen frei sein','Nebel/Regen schwächen'],
      fehlalarm:['Vögel im Strahl','Schnee/Nebel','Bewegliche Pflanzen'],
      montage:'Sender + Empfänger gegenüber, exakt fluchtend',
      normen:['VdS 2358','DIN EN 50131-2-5'],
      sue:'2-5', preis:'80–1.200 €',
      hersteller:['Optex','SICK','Banner'],
      ill:'irBeam', icon:'fa-arrows-left-right'
    },

    // ============= BRANDMELDER =============
    {
      key:'rauch-streulicht', kat:'Brand', name:'Optischer Rauchmelder (Streulicht)',
      type:'aktiv', principle:'Tyndall-Effekt',
      physik:'LED beleuchtet eine dunkle Detektionskammer im rechten Winkel zum Foto-Sensor. Im Normalfall: kein Licht am Sensor. Bei Rauch: Rauchpartikel streuen LED-Licht → trifft Sensor → Alarm.',
      sendet:'LED-Licht in dunkle Kammer',
      coverage:'flaeche · 60–80 m²', range:'Raumdecke',
      zone:[3],
      staerken:['Universal-Brandmelder','Sehr verbreitet','Günstig'],
      schwaechen:['Erkennt nur Schwelbrand-Rauch zuverlässig','Anfällig für Staub'],
      fehlalarm:['Staub','Wasserdampf','Insekten in der Kammer'],
      montage:'Raumdecke, mittig',
      normen:['DIN EN 54-7'],
      sue:'alle', preis:'20–80 €',
      hersteller:['Siemens','Hekatron','Bosch'],
      ill:'fire', icon:'fa-smog'
    },
    {
      key:'waerme-max', kat:'Brand', name:'Thermischer Melder (Maximum)',
      type:'passiv', principle:'Temperaturgrenze',
      physik:'Thermistor misst Raumtemperatur. Alarm bei Überschreiten eines festen Grenzwerts (typ. >54 °C).',
      sendet:'nichts',
      coverage:'flaeche · 30–40 m²', range:'Raumdecke',
      zone:[3],
      staerken:['Keine Fehlalarme durch Staub','Geeignet für Küchen/Garagen'],
      schwaechen:['Spricht erst bei offener Flamme an','Spät'],
      fehlalarm:['Sehr selten'],
      montage:'Raumdecke',
      normen:['DIN EN 54-5'],
      sue:'alle', preis:'25–90 €',
      hersteller:['Siemens','Hekatron'],
      ill:'fire', icon:'fa-temperature-high'
    },
    {
      key:'multisensor', kat:'Brand', name:'Multisensor-Brandmelder',
      type:'aktiv (LED)', principle:'Rauch + Wärme kombiniert',
      physik:'Kombiniert optischen Streulicht-Sensor mit Thermistor. Beide Werte werden kombiniert ausgewertet → deutlich weniger Fehlalarme bei gleichzeitiger Detektion früher Brandphasen.',
      sendet:'LED in Streulicht-Kammer',
      coverage:'flaeche · 60–80 m²', range:'Raumdecke',
      zone:[3],
      staerken:['Universal, wenig Fehlalarme','Erkennt früh','Standard ab BMA'],
      schwaechen:['Teurer als einfacher Rauchmelder'],
      fehlalarm:['Gering – nur bei extremen Bedingungen'],
      montage:'Raumdecke',
      normen:['DIN EN 54-29'],
      sue:'alle', preis:'50–150 €',
      hersteller:['Siemens','Esser','Hekatron'],
      ill:'fire', icon:'fa-fire-flame-curved'
    },
    {
      key:'asd', kat:'Brand', name:'Ansaugrauchmelder (ASD)',
      type:'aktiv', principle:'Aktive Luftansaugung + Laser-Detektion',
      physik:'Ein Rohrnetz saugt permanent Luft aus dem überwachten Raum an. Die Luft wird einer hochempfindlichen Laser-Detektionseinheit zugeführt, die Rauchpartikel-Konzentrationen unterhalb der Sichtbarkeit erkennt.',
      sendet:'Pumpe saugt Luft, Laserstrahl analysiert',
      coverage:'flaeche · bis 2.000 m²', range:'sehr großflächig',
      zone:[3],
      staerken:['Frühste Branderkennung','Sehr große Flächen','Ideal für Server, Archive, Museen'],
      schwaechen:['Teuer','Wartung der Pumpe nötig'],
      fehlalarm:['Sehr gering'],
      montage:'Zentrale + Rohrnetz an der Decke',
      normen:['DIN EN 54-20'],
      sue:'3-6', preis:'1.500–5.000 €',
      hersteller:['Wagner','Xtralis','Securiton'],
      ill:'fire', icon:'fa-wind'
    },
    {
      key:'flammenmelder', kat:'Brand', name:'Flammenmelder (IR/UV)',
      type:'passiv', principle:'UV/IR-Detektion',
      physik:'Sensor empfängt UV-Strahlung (185–260 nm) und/oder IR-Strahlung (~4,3 µm) von Flammen. Spektral-Analyse unterscheidet Flammen von Sonnenlicht.',
      sendet:'nichts',
      coverage:'volumetrisch · Sichtlinie', range:'10–30 m',
      zone:[3,1],
      staerken:['Sofort-Alarm bei offener Flamme','Für Industrie / Tankstellen'],
      schwaechen:['Braucht Sichtlinie','Spezialanwendung'],
      fehlalarm:['Schweißarbeiten','Sonnenreflexe','Lichtbögen'],
      montage:'Wand mit Sichtlinie auf Risikobereich',
      normen:['DIN EN 54-10'],
      sue:'3-5', preis:'300–1.500 €',
      hersteller:['Det-Tronics','Siemens'],
      ill:'fire', icon:'fa-fire'
    },

    // ============= PERIMETER-SENSORIK =============
    {
      key:'zaun-mikro', kat:'Perimeter', name:'Mikrophonische Zaunsensorik',
      type:'passiv', principle:'Mikrofon-Kabel am Zaun',
      physik:'Spezielles Sensorkabel mit eingebetteten Mikrofonen entlang des Zauns. Erfasst Vibration/Akustik beim Schneiden, Klettern, Manipulieren. Auswerteeinheit analysiert Signaturen.',
      sendet:'nichts',
      coverage:'linie · Zaun-Strecke', range:'bis 600 m pro Zone',
      zone:[1],
      staerken:['Kein Maintenance pro Sensor','Lange Reichweiten','Robuste Erkennung'],
      schwaechen:['Kann durch Wetter beeinflusst werden','Justage nötig'],
      fehlalarm:['Sturm','Tiere am Zaun','Verkehr'],
      montage:'an Zaunfelder geklemmt',
      normen:['DIN EN 50131-2-7','VdS 2358'],
      sue:'3-5', preis:'80–150 €/m',
      hersteller:['Sorhea','Senstar','Gallagher'],
      ill:'fence', icon:'fa-grip-lines'
    },
    {
      key:'zaun-fos', kat:'Perimeter', name:'Glasfaser-Zaunsensorik (FOS)',
      type:'aktiv', principle:'Lichtlaufzeit (OTDR)',
      physik:'Ein Laserimpuls läuft durch Glasfaser entlang des Zauns. Vibrationen verändern die Lichtlaufzeit. Optical Time Domain Reflectometer (OTDR) misst und lokalisiert die Störung auf wenige Meter genau.',
      sendet:'Laser-Lichtimpulse durch Glasfaser',
      coverage:'linie · sehr lang', range:'bis 40 km',
      zone:[1],
      staerken:['Sehr lange Reichweite','Genaue Lokalisierung','Nicht überbrückbar (kein Strom)'],
      schwaechen:['Teure Auswerteinheit','Glasfaser-Verlegung nötig'],
      fehlalarm:['Reduziert durch KI-Auswertung'],
      montage:'Glasfaser entlang Zaun verlegen',
      normen:['DIN EN 50131-2-7'],
      sue:'5-6', preis:'50–120 €/m',
      hersteller:['Senstar','OptaSense','Bandweaver'],
      ill:'fence', icon:'fa-route'
    },
    {
      key:'thermalkam', kat:'Perimeter', name:'Thermalkamera + KI',
      type:'passiv', principle:'Wärmebild + KI-Auswertung',
      physik:'Mikrobolometer-Sensor erfasst Wärmestrahlung im Bereich 8–14 µm und erzeugt Wärmebild. KI-Algorithmen erkennen Personen/Fahrzeuge auch bei Nacht, Nebel, Regen.',
      sendet:'nichts (passiv)',
      coverage:'volumetrisch · Bildausschnitt', range:'100–2.000 m',
      zone:[1],
      staerken:['Funktioniert bei 100 % Dunkelheit','Erkennt durch Tarnung/Regen','KI verifiziert Alarm'],
      schwaechen:['Sehr teuer','Aufwendige Auswertung'],
      fehlalarm:['Sehr gering durch KI'],
      montage:'erhöht (Mast), 360° schwenkbar',
      normen:['DIN EN 62676-4'],
      sue:'3-6', preis:'3.000–15.000 €',
      hersteller:['Axis','FLIR','Hikvision'],
      ill:'fence', icon:'fa-camera'
    },
    {
      key:'radar', kat:'Perimeter', name:'Radar',
      type:'aktiv', principle:'Radar-Wellen, Reflexion + Doppler',
      physik:'Mikrowellen-Radar (24/77 GHz) sendet Wellen aus, misst Reflexionen und Doppler-Verschiebung. Erkennt bewegte Objekte präzise nach Geschwindigkeit und Position.',
      sendet:'Mikrowellen 24/77 GHz',
      coverage:'volumetrisch · Sektor', range:'bis 500 m',
      zone:[1],
      staerken:['Wetterunabhängig','Erkennt Geschwindigkeit + Richtung','Große Reichweite'],
      schwaechen:['Sehr teuer','Aufwendige Auswertung','Sichtlinie nötig'],
      fehlalarm:['Großvögel','Bewegte Vegetation'],
      montage:'erhöht, freie Sicht ins Areal',
      normen:['DIN EN 50131-2-3'],
      sue:'4-6', preis:'5.000–20.000 €',
      hersteller:['Navtech','Spotter','Hensoldt'],
      ill:'fence', icon:'fa-satellite-dish'
    },
    {
      key:'lidar', kat:'Perimeter', name:'LiDAR',
      type:'aktiv', principle:'Laser-Scanner',
      physik:'Rotierender Laser sendet Lichtimpulse, misst Laufzeit und erstellt 3D-Punktwolke. KI klassifiziert Objekte (Mensch/Tier/Fahrzeug) und Bewegungsmuster.',
      sendet:'Laser-Lichtimpulse',
      coverage:'volumetrisch · 3D-Scan', range:'50–300 m',
      zone:[1],
      staerken:['Präzise 3D-Vermessung','Wetterrobust','Objekt-Klassifikation'],
      schwaechen:['Sehr teuer','Pflegebedarf'],
      fehlalarm:['Sehr gering durch KI'],
      montage:'erhöht, kalibriert',
      normen:['DIN EN 50131'],
      sue:'5-6', preis:'10.000–50.000 €',
      hersteller:['Velodyne','Hesai','Quanergy'],
      ill:'fence', icon:'fa-radar'
    },
    {
      key:'erddruck', kat:'Perimeter', name:'Erddruck-/Geophon',
      type:'passiv', principle:'Seismische Detektion im Boden',
      physik:'Sensoren werden vergraben und reagieren auf Bodenerschütterungen durch Schritte oder Fahrzeuge. Mustererkennung unterscheidet Tiere von Menschen.',
      sendet:'nichts',
      coverage:'linie · entlang Erdkabel', range:'bis 200 m',
      zone:[1],
      staerken:['Unsichtbar','Schwer zu umgehen','Robust'],
      schwaechen:['Aufwendige Verlegung','Bodenbeschaffenheit kritisch'],
      fehlalarm:['Großtiere','Erdarbeiten'],
      montage:'10–20 cm tief eingegraben',
      normen:['DIN EN 50131-2-6'],
      sue:'4-6', preis:'2.000–5.000 €/Stk',
      hersteller:['Senstar','Cias'],
      ill:'fence', icon:'fa-earth-europe'
    },

    // ============= SONDER / ZK / KAMERA (kurz) =============
    {
      key:'neigung', kat:'Spezial', name:'Neigungssensor',
      type:'aktiv (Gyro)', principle:'Gyrosensor / Inklinometer',
      physik:'MEMS-Sensor misst Lageänderung. Bei Kippen oder Umwerfen des Objekts → Winkeländerung > Schwellwert → Alarm.',
      sendet:'kleinen Sensor-Eigenverbrauch',
      coverage:'punkt · pro Objekt', range:'pro Objekt',
      zone:[4],
      staerken:['Erkennt Kippen/Umwerfen sofort','Klein','Ideal für Geldautomaten'],
      schwaechen:['Reagiert nicht auf andere Angriffe'],
      fehlalarm:['Vibrationen während Transport','Erdbeben'],
      montage:'fest im Objekt',
      normen:[],
      sue:'3-5', preis:'30–100 €',
      hersteller:['Bosch','TE Connectivity'],
      ill:'shake', icon:'fa-angle-up'
    },
  ];

  return { list: M };
})();
