/* Zusätzliche Spezialmelder für die Enzyklopädie */
(function() {
  function add() {
    if (!window.ENCY) return;
    const extras = [
      {
        key:'alarmdraht-tapete', kat:'Wandschutz', name:'Alarmdraht-Tapete',
        type:'aktiv (Stromüberwachung)', principle:'Eingebettete Leiterbahnen in der Wandtapete',
        physik:'In die Tapete sind hauchdünne Drähte (Alarmschlaufe) flächendeckend eingebettet. Niedriger Ruhestrom fließt permanent durch das gesamte Netz. Sobald jemand durch die Wand zu bohren oder zu brechen versucht, wird einer der Drähte unterbrochen → Stromfluss=0 → ALARM.',
        sendet:'kleiner Prüfstrom (mA) durch die Drahtschleife',
        coverage:'flaeche · Wand-/Deckenfläche', range:'pro Wand bis 60 m² je Stromkreis',
        zone:[2,4],
        staerken:['Optisch unsichtbar (hinter Tapete)','100 % Wand-Durchbruch-Erkennung','Sehr robust gegen Sabotage','Tresor-Standard SÜ 5-6'],
        schwaechen:['Aufwendige Verlegung','Bei Renovierung neu','Nur einmal nutzbar (kein Wiederverwenden)'],
        fehlalarm:['Kabelriss bei Nagel-/Bohrarbeit','Materialschäden durch Feuchtigkeit'],
        montage:'Unter spezieller Tapete oder Putz',
        normen:['VdS 2227','DIN EN 50131-2-7'],
        sue:'4-6', preis:'40–120 €/m²',
        hersteller:['Telenot','Honeywell','Geba'],
        ill:'glass', icon:'fa-grip-lines-vertical'
      },
      {
        key:'alarmspinne', kat:'Objektschutz', name:'Alarmspinne',
        type:'aktiv (Stromüberwachung)', principle:'Drahtgewebe spinnenartig auf zu schützender Fläche',
        physik:'Ein engmaschiges Drahtgeflecht wird in Spinnen- oder Rautenform auf eine Vitrine, Tresor-Tür oder Wand-Element aufgebracht. Niedriger Strom fließt durch das Geflecht. Jeder Versuch, das Objekt zu durchbrechen, durchtrennt mindestens einen Draht → ALARM. Wie ein Spinnennetz quer über die Fläche gespannt.',
        sendet:'permanenter Prüfstrom durch das Geflecht',
        coverage:'flaeche · pro Objekt', range:'pro Vitrine/Tresor-Element',
        zone:[4],
        staerken:['Sehr engmaschig — kein Bohrloch unentdeckt','Schwer zu umgehen','Sichtbar als optische Abschreckung möglich'],
        schwaechen:['Bei Wartung problematisch','Nicht für große Flächen'],
        fehlalarm:['Materialermüdung','Korrosion bei feuchten Bedingungen'],
        montage:'Direkt auf Vitrinen-Glas, Tresorrückwand, Decke',
        normen:['VdS 2227'],
        sue:'4-6', preis:'80–300 €/m²',
        hersteller:['Telenot','Geba'],
        ill:'glass', icon:'fa-grip'
      },
      {
        key:'alarmschlinge', kat:'Objektschutz', name:'Alarmschlinge / Fangschlinge',
        type:'aktiv (Stromüberwachung)', principle:'Dünner Draht in Schlaufe um wertvolles Objekt',
        physik:'Ein hauchdünner Alarmdraht wird wie eine Schlinge um ein wertvolles Objekt (Gemälde, Skulptur, Vitrinen-Element) gespannt. Permanenter Ruhestrom. Sobald das Objekt entfernt oder bewegt wird, wird die Schlaufe durchtrennt oder gedehnt → ALARM.',
        sendet:'Prüfstrom durch die Schlaufe',
        coverage:'punkt · pro Objekt', range:'pro Objekt',
        zone:[4],
        staerken:['Sehr einfach','Ideal für Kunst, Pelze, Vitrinen','Optisch unauffällig (transparent möglich)'],
        schwaechen:['Nur für einzelne Objekte','Kann von Profi durchtrennt werden'],
        fehlalarm:['Materialermüdung','Schwingungen bei Trans-port'],
        montage:'Direkt am Objekt befestigt',
        normen:['VdS 2227'],
        sue:'3-5', preis:'20–80 €/Stk',
        hersteller:['Telenot','Geba'],
        ill:'glass', icon:'fa-link'
      },
      {
        key:'kontaktmatte-hub', kat:'Vitrinenschutz', name:'Hub-Kontaktmatte',
        type:'passiv', principle:'Mechanischer Kontakt unter Vitrinen-Hubglas',
        physik:'Eine dünne Kontaktmatte liegt unter dem Hubglas einer Vitrine. Solange das Glas auf der Matte liegt, ist der Kontakt geschlossen (Ruhestrom). Beim Anheben des Glases öffnet sich der Kontakt → ALARM. Häufig kombiniert mit Magnetkontakt für Doppelsicherheit.',
        sendet:'nichts',
        coverage:'punkt · pro Vitrine', range:'pro Vitrine',
        zone:[4],
        staerken:['Sehr zuverlässig (mechanisch)','Schwer zu täuschen','Günstig'],
        schwaechen:['Funktioniert nur bei Hubglas-Vitrinen','Verschleißteil'],
        fehlalarm:['Vibration durch Lautsprecher','Verformtes Glas'],
        montage:'Unter dem Hubglas-Rand',
        normen:['VdS 2227','DIN EN 50131-2-6'],
        sue:'3-5', preis:'30–80 €',
        hersteller:['Telenot','Honeywell'],
        ill:'press', icon:'fa-arrow-up-from-bracket'
      },
      {
        key:'lwl-bruch', kat:'Wandschutz', name:'Lichtwellenleiter-Bruchmelder',
        type:'aktiv', principle:'Laserlicht in Glasfaser unter Putz/Tapete',
        physik:'Eine Glasfaser wird in Schleifen unter Putz, hinter der Tapete oder in der Decke verlegt. Ein Laser sendet permanent Lichtimpulse durch die Faser. Bricht ein Einbrecher durch die Wand, wird die Glasfaser geknickt oder zerstört → Lichtsignal bricht ab → ALARM. Sehr empfindlich, schwer zu sabotieren.',
        sendet:'Laser-Licht (~1550 nm) durch die Faser',
        coverage:'flaeche · Wand mit verlegter Faser', range:'bis 10 km pro Faser',
        zone:[2,4],
        staerken:['Höchste Sicherheit','EMV-fest (Glasfaser leitet nicht)','Sehr lange Reichweite','Nicht überbrückbar'],
        schwaechen:['Teure Verlegung','Spezielle Auswerteinheit nötig'],
        fehlalarm:['Sehr gering – nur bei echten Bauarbeiten'],
        montage:'Hinter Tapete / unter Putz verlegt',
        normen:['VdS 2227'],
        sue:'5-6', preis:'30–80 €/m',
        hersteller:['Senstar','Bandweaver','OptaSense'],
        ill:'fence', icon:'fa-route'
      },
      {
        key:'tuergriff-sensor', kat:'Sabotageschutz', name:'Türgriff-Berührungssensor',
        type:'aktiv (kapazitiv)', principle:'Kapazitive Berührungserkennung am Türgriff',
        physik:'In den Türgriff ist eine kapazitive Elektrode integriert. Sobald jemand den Griff berührt, ändert sich die Kapazität durch den menschlichen Körper. Sofortige Erkennung VOR dem Drücken/Öffnen der Tür. Ideal für Vorwarn-Systeme oder zur Erkennung von Manipulationsversuchen.',
        sendet:'elektrostatisches Feld am Griff',
        coverage:'punkt · am Türgriff', range:'pro Griff',
        zone:[2],
        staerken:['Erkennt JEDEN Annäherungsversuch','Vorwarnung bevor Tür geöffnet wird','Unauffällig'],
        schwaechen:['Nur bei Berührung','Nicht für Notausgänge'],
        fehlalarm:['Versehentliches Berühren','Hund im Treppenhaus'],
        montage:'Im Türgriff integriert',
        normen:['VdS 2227'],
        sue:'3-5', preis:'80–200 €',
        hersteller:['Burg-Wächter','dormakaba','Telenot'],
        ill:'cap', icon:'fa-hand'
      },
      {
        key:'hall-sensor', kat:'Sabotageschutz', name:'Hall-Effekt-Sensor (Metall)',
        type:'aktiv', principle:'Magnetfeld-Sensor erkennt Metallnähe',
        physik:'Hall-Sensor misst kontinuierlich das Erdmagnetfeld in der Umgebung. Sobald ein metallisches Werkzeug (Hebeleisen, Säge, Bolzenschneider) angenähert wird, verzerrt es das Magnetfeld → Hall-Spannung ändert sich → Werkzeug-Annäherung erkannt → ALARM oder Vorwarnung.',
        sendet:'Stromfluss durch Hall-Plättchen',
        coverage:'feld · 0,5–2 m Annäherung', range:'~1 m vor dem Sensor',
        zone:[4],
        staerken:['Erkennt Werkzeuge VOR Angriff','Funktioniert durch nicht-magnetische Materialien','Klein und kostengünstig'],
        schwaechen:['Reagiert auf Mobiltelefone in der Nähe','Geomagnetische Stürme können stören'],
        fehlalarm:['Stahlteile in Schuhen','Magnetische Werkzeuge bei Wartung'],
        montage:'Hinter Tresor-Wand oder Geldautomat',
        normen:['DIN EN 50131-2-9'],
        sue:'4-6', preis:'40–120 €',
        hersteller:['Honeywell','Bosch','Allegro'],
        ill:'cap', icon:'fa-magnet'
      },
      {
        key:'wandungsmelder', kat:'Tresorschutz', name:'Wandungsmelder (Penetration)',
        type:'aktiv (Stromüberwachung)', principle:'Drahtgitter in Tresor-Stahlwand eingegossen',
        physik:'Speziell für Tresorräume und Hochsicherheits-Wände: In die Stahlbeton-Wand wird ein engmaschiges Drahtgitter mit eingegossen. Permanenter Ruhestrom. Jeder Versuch, durch die Wand zu bohren, zu fräsen oder zu schneiden, durchtrennt mindestens einen Draht → ALARM.',
        sendet:'permanenter Prüfstrom (mA)',
        coverage:'flaeche · gesamte Wand', range:'pro Wand',
        zone:[4],
        staerken:['Höchste Sicherheit','Durch jede Stelle der Wand erkennbar','Standard für Tresorräume'],
        schwaechen:['Nur bei Neubau möglich','Aufwendig + teuer'],
        fehlalarm:['Sehr gering'],
        montage:'In Stahlbeton eingegossen (bei Bau)',
        normen:['VdS 2480','EN 1143-1'],
        sue:'6', preis:'200–500 €/m²',
        hersteller:['Wertheim','Mauer','Burg-Wächter'],
        ill:'shake', icon:'fa-shield-halved'
      },
      {
        key:'rauchansaug-glas', kat:'Sondermelder', name:'Glasbruch-Detektor mit Rauch (kombiniert)',
        type:'hybrid', principle:'Akustischer Glasbruch + ASD-Rauchüberwachung',
        physik:'Kombiniertes Modul aus Glasbruch-Akustiksensor (passiv) und Mini-Ansaugrauchmelder (aktiv). Wird bei Schaufenstern und Vitrinen eingesetzt, wo sowohl Glasbruch (Einbruch) als auch Brand (Sabotage) erkannt werden müssen. Ein Gehäuse, zwei unabhängige Alarme.',
        sendet:'Saugpumpe für Luftanalyse + passives Mikrofon',
        coverage:'flaeche', range:'6 m Akustik + Raum-Ansaugung',
        zone:[2,4],
        staerken:['Einbruch + Brand in einem Gerät','Sehr früh-warnsam','Platz-effizient'],
        schwaechen:['Teurer','Mehr Wartungsaufwand'],
        fehlalarm:['Pumpen-Verschmutzung','Lärm-Bursts (durch Doppel-Auswertung gemindert)'],
        montage:'An Vitrinen/Schaufenstern, Decke',
        normen:['VdS 2332 + DIN EN 54-20'],
        sue:'4-6', preis:'600–1.500 €',
        hersteller:['Wagner','Securiton','Telenot'],
        ill:'glass', icon:'fa-fire'
      },
      {
        key:'inertialer-sensor', kat:'Geldautomat', name:'Inertialsensor (Beschleunigung)',
        type:'aktiv (MEMS)', principle:'MEMS-Beschleunigungssensor erkennt jede Bewegung des Objekts',
        physik:'Mikro-mechanischer MEMS-Sensor misst 3-Achsen-Beschleunigung mit hoher Auflösung (0,01 m/s²). Erkennt jedes Anstoßen, Verschieben, Anheben oder Aufprallen. Wird in Geldautomaten, Kunst-Skulpturen und Wert-Behältnissen eingesetzt.',
        sendet:'Stromfluss durch MEMS-Strukturen',
        coverage:'punkt · im Objekt', range:'pro Objekt',
        zone:[4],
        staerken:['3-Achsen-Erkennung','Sehr klein und günstig','Auch bei feinster Bewegung'],
        schwaechen:['Reagiert auf Erschütterungen (LKW)','Drift über Zeit'],
        fehlalarm:['Erdbeben','Bauarbeiten in der Nähe'],
        montage:'Fest im Objekt verbaut',
        normen:['DIN EN 50131-2-9'],
        sue:'3-5', preis:'15–60 €',
        hersteller:['Bosch Sensortec','STMicroelectronics','TDK InvenSense'],
        ill:'shake', icon:'fa-arrows-up-down'
      },
    ];
    // Append to ENCY.list
    extras.forEach(e => ENCY.list.push(e));
  }
  if (window.ENCY) add(); else document.addEventListener('DOMContentLoaded', add);
})();
